In [40]:
import pandas as pd

In [41]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [47]:
data_set = pd.read_csv('/content/drive/MyDrive/Summarization/collection_data/collection_dataset.csv', encoding='utf-8')
data_set

,urls,titles,keywords,tldrs,abstracts,one_sentence_summ
0,https://openreview.net/forum?id=Sy8gdB9xx,Understanding deep learning requires rethinkin...,Deep learning,"Through extensive systematic experiments, we s...","Despite their massive size, successful deep ar...",NaN
1,https://openreview.net/forum?id=r1Ue8Hcxg,Neural Architecture Search with Reinforcement ...,NaN,NaN,Neural networks are powerful and flexible mode...,NaN
2,https://openreview.net/forum?id=Hk4_qw5xe,Towards Principled Methods for Training Genera...,NaN,We introduce a theory about generative adversa...,The goal of this paper is not to introduce a s...,NaN
3,https://openreview.net/forum?id=HJ0NvFzxl,Learning Graphical State Transitions,Natural language processing; Deep learning; Su...,I introduce a set of differentiable graph tran...,Graph-structured data is important in modeling...,NaN
4,https://openreview.net/forum?id=HkwoSDPgg,Semi-supervised Knowledge Transfer for Deep Le...,NaN,Semi-supervised learning of a privacy-preservi...,Some machine learning applications involve tra...,NaN
...,...,...,...,...,...,...
24473,https://openreview.net/forum?id=1bbPQShCT2,I-PHYRE: Interactive Physical Reasoning,Intuitive physics; physical reasoning,Build human-level interactive agents that can ...,Current evaluation protocols predominantly ass...,NaN
24474,https://openreview.net/forum?id=Ny150AblPu,Exposing Text-Image Inconsistency Using Diffus...,inconsistency detection; multi-modal learning;...,NaN,In the battle against widespread online misinf...,NaN
24475,https://openreview.net/forum?id=ZGBOfAQrMl,Video Super-Resolution Transformer with Masked...,video super-resolution; adaptive; memory and c...,NaN,"Recently, Vision Transformer has achieved grea...",NaN
24476,https://openreview.net/forum?id=J2kRjUAOLh,Contrastive Predict-and-Search for Mixed Integ...,Mixed integer programs; contrastive learning,We use contrastive learning to predict solutio...,Mixed integer linear programs (MILP) are flex...,NaN
24477,https://openreview.net/forum?id=U0P622bfUN,Federated Generative Learning with Foundation ...,federated learning; non-iid data,We propose a novel federated learning framewor...,Existing federated learning solutions focus on...,NaN

In [43]:
data_set[['tldrs', 'one_sentence_summ']]

                                                   tldrs one_sentence_summ
0      Through extensive systematic experiments, we s...               NaN
1                                                    NaN               NaN
2      We introduce a theory about generative adversa...               NaN
3      I introduce a set of differentiable graph tran...               NaN
4      Semi-supervised learning of a privacy-preservi...               NaN
...                                                  ...               ...
24473  Build human-level interactive agents that can ...               NaN
24474                                                NaN               NaN
24475                                                NaN               NaN
24476  We use contrastive learning to predict solutio...               NaN
24477  We propose a novel federated learning framewor...               NaN

[24478 rows x 2 columns]

In [44]:
data_set['tldrs'].isna().sum()

12581

In [45]:
data_set['one_sentence_summ'].isna().sum()

19399

In [67]:
null_list = []
for i in range(len(data_set)):
  if pd.isna(data_set['one_sentence_summ'][i]) and pd.isna(data_set['tldrs'][i]):
    null_list.append(i)
print(null_list)
print(len(null_list))

[1, 6, 12, 15, 17, 31, 33, 34, 35, 36, 38, 55, 56, 60, 67, 68, 69, 70, 72, 75, 80, 82, 84, 86, 88, 89, 91, 92, 96, 97, 99, 101, 103, 110, 119, 122, 124, 125, 127, 128, 129, 131, 134, 135, 138, 139, 140, 144, 150, 154, 159, 163, 168, 172, 174, 177, 179, 183, 189, 193, 195, 200, 201, 214, 215, 216, 219, 225, 228, 230, 236, 239, 246, 250, 262, 264, 271, 274, 277, 279, 282, 289, 291, 292, 294, 297, 298, 300, 315, 320, 322, 326, 334, 335, 339, 340, 343, 344, 348, 353, 355, 359, 360, 365, 371, 373, 381, 384, 392, 401, 415, 422, 423, 424, 425, 427, 429, 432, 434, 435, 436, 442, 450, 453, 461, 462, 463, 466, 467, 468, 477, 480, 482, 483, 485, 487, 494, 495, 503, 508, 511, 519, 522, 526, 532, 540, 548, 554, 560, 561, 564, 580, 583, 586, 588, 589, 592, 603, 605, 610, 611, 621, 626, 651, 656, 662, 664, 668, 671, 678, 688, 702, 703, 705, 706, 708, 709, 711, 712, 716, 720, 724, 727, 729, 736, 739, 744, 757, 764, 769, 791, 799, 802, 803, 807, 823, 826, 828, 832, 834, 846, 859, 861, 863, 867, 871, 883, 894, 895, 896, 897, 898, 899, 901, 906, 914, 920, 924, 927, 928, 931, 946, 950, 961, 962, 974, 979, 992, 994, 996, 997, 998, 1006, 1009, 1010, 1014, 1017, 1019, 1021, 1032, 1033, 1040, 1043, 1048, 1049, 1065, 1072, 1073, 1077, 1082, 1083, 1084, 1086, 1089, 1090, 1094, 1098, 1112, 1113, 1115, 1131, 1135, 1136, 1146, 1148, 1149, 1160, 1161, 1166, 1167, 1168, 1171, 1172, 1186, 1187, 1189, 1191, 1192, 1196, 1204, 1207, 1212, 1214, 1220, 1228, 1232, 1235, 1242, 1246, 1251, 1255, 1259, 1263, 1266, 1274, 1277, 1280, 1282, 1286, 1305, 1307, 1312, 1317, 1318, 1326, 1336, 1343, 1344, 1346, 1347, 1352, 1357, 1359, 1360, 1361, 1363, 1364, 1365, 1368, 1379, 1380, 1382, 1385, 1386, 1387, 1390, 1397, 1409, 1416, 1417, 1418, 1430, 1431, 1433, 1442, 1444, 1445, 1448, 1449, 1462, 1464, 1465, 1466, 1471, 1472, 1473, 1477, 1478, 1480, 1495, 1508, 1511, 1525, 1530, 1540, 1546, 1547, 1550, 1552, 1554, 1558, 1565, 1579, 1580, 1582, 1594, 1596, 1599, 1600, 1602, 1604, 1606, 1610, 1611, 1613, 1614, 1616, 1630, 1635, 1640, 1642, 1645, 1648, 1666, 1680, 1687, 1689, 1692, 1693, 1697, 1707, 1711, 1712, 1716, 1719, 1722, 1723, 1727, 1728, 1735, 1742, 1743, 1744, 1753, 1764, 1775, 1780, 1784, 1786, 1788, 1789, 1790, 1800, 1802, 1803, 1804, 1818, 1819, 1820, 1824, 1827, 1828, 1834, 1838, 1842, 1846, 1851, 1857, 1859, 1875, 1882, 1890, 1892, 1898, 1900, 1908, 1909, 1912, 1928, 1941, 1943, 1949, 1950, 1955, 1964, 1966, 1967, 1969, 1978, 1981, 1983, 1989, 1993, 1996, 1998, 2001, 2015, 2020, 2022, 2023, 2025, 2030, 2034, 2035, 2038, 2043, 2044, 2045, 2047, 2056, 2073, 2078, 2081, 2086, 2088, 2090, 2098, 2103, 2104, 2105, 2108, 2114, 2132, 2137, 2141, 2147, 2149, 2151, 2153, 2156, 2164, 2171, 2181, 2195, 2199, 2201, 2207, 2210, 2211, 2221, 2223, 2227, 2231, 2233, 2240, 2241, 2249, 2262, 2263, 2272, 2279, 2283, 2287, 2288, 2289, 2290, 2293, 2307, 2311, 2314, 2317, 2321, 2331, 2332, 2335, 2339, 2343, 2350, 2354, 2357, 2363, 2364, 2369, 2373, 2376, 2379, 2382, 2383, 2386, 2396, 2403, 2405, 2413, 2415, 2416, 2431, 2445, 2453, 2458, 2460, 2467, 2468, 2469, 2470, 2471, 2473, 2485, 2490, 2491, 2496, 2510, 2511, 2516, 2521, 2530, 2536, 2537, 2539, 2544, 2549, 2551, 2552, 2557, 2565, 2566, 2568, 2569, 2571, 2573, 2579, 2586, 2588, 2589, 2591, 2594, 2596, 2597, 2600, 2606, 2610, 2624, 2636, 2637, 2642, 2643, 2651, 2657, 2659, 2662, 2664, 2670, 2676, 2678, 2679, 2681, 2682, 2685, 2692, 2694, 2700, 2704, 2707, 2711, 2715, 2728, 2729, 2733, 2738, 2739, 2743, 2747, 2748, 2757, 2759, 2762, 2765, 2767, 2770, 2776, 2777, 2778, 2779, 2780, 2784, 2788, 2789, 2793, 2798, 2799, 2811, 2813, 2814, 2816, 2822, 2823, 2829, 2834, 2848, 2850, 2851, 2859, 2860, 2863, 2864, 2866, 2872, 2873, 2875, 2876, 2881, 2884, 2887, 2891, 2897, 2898, 2899, 2903, 2906, 2909, 2917, 2923, 2933, 2936, 2937, 2944, 2946, 2950, 2951, 2959, 2960, 2974, 2976, 2978, 2980, 2984, 2985, 2988, 2989, 2990, 2992, 2996, 3000, 3004, 3007, 3011, 3018, 3020, 3024, 3027, 3038, 3044, 3045, 3046, 3048, 3050, 3051, 3052, 3055, 3067, 3071, 3077, 3079, 3081, 3082, 3084, 3089, 3094, 3103, 3108, 3117, 3118, 3134, 3153, 3158, 3162, 3169, 3180, 3189, 3197, 3200, 3206, 3208, 3217, 3219, 3222, 3229, 3236, 3250, 3259, 3261, 3262, 3263, 3266, 3269, 3270, 3275, 3278, 3279, 3280, 3284, 3299, 3300, 3301, 3304, 3305, 3309, 3310, 3314, 3321, 3324, 3326, 3332, 3333, 3336, 3342, 3343, 3345, 3349, 3356, 3359, 3369, 3370, 3377, 3378, 3383, 3384, 3387, 3388, 3394, 3395, 3400, 3410, 3411, 3413, 3417, 3424, 3431, 3436, 3439, 3440, 3447, 3448, 3456, 3457, 3461, 3465, 3470, 3478, 3481, 3486, 3488, 3489, 3496, 3507, 3509, 3516, 3521, 3522, 3523, 3524, 3526, 3531, 3537, 3542, 3544, 3548, 3553, 3558, 3560, 3566, 3567, 3568, 3572, 3578, 3581, 3585, 3589, 3595, 3597, 3598, 3605, 3606, 3613, 3625, 3626, 3629, 3630, 3631, 3638, 3642, 3645, 3647, 3656, 3666, 3676, 3678, 3681, 3682, 3690, 3692, 3693, 3698, 3701, 3708, 3711, 3716, 3720, 3726, 3727, 3731, 3733, 3735, 3738, 3739, 3743, 3760, 3774, 3777, 3786, 3787, 3790, 3799, 3801, 3804, 3808, 3815, 3831, 3834, 3836, 3839, 3842, 3845, 3847, 3848, 3851, 3855, 3857, 3861, 3862, 3863, 3871, 3873, 3879, 3888, 3893, 3897, 3899, 3904, 3905, 3907, 3915, 3916, 3925, 3928, 3931, 3939, 3944, 3945, 3947, 3953, 3955, 3968, 3973, 3979, 3981, 3983, 3988, 3990, 3992, 3998, 3999, 4001, 4002, 4005, 4006, 4014, 4016, 4021, 4023, 4030, 4032, 4036, 4039, 4045, 4047, 4049, 4055, 4058, 4061, 4062, 4063, 4071, 4075, 4077, 4085, 4086, 4093, 4098, 4106, 4107, 4110, 4111, 4112, 4113, 4115, 4116, 4118, 4120, 4122, 4124, 4128, 4133, 4135, 4137, 4140, 4146, 4154, 4155, 4156, 4158, 4161, 4162, 4163, 4175, 4181, 4184, 4186, 4187, 4201, 4203, 4211, 4215, 4216, 4219, 4220, 4225, 4226, 4232, 4234, 4241, 4246, 4256, 4257, 4258, 4264, 4266, 4272, 4307, 4316, 4319, 4322, 4329, 4347, 4350, 4351, 4355, 4358, 4359, 4365, 4369, 4371, 4372, 4373, 4375, 4380, 4381, 4382, 4390, 4393, 4396, 4397, 4402, 4406, 4409, 4418, 4420, 4421, 4422, 4432, 4436, 4438, 4453, 4456, 4462, 4466, 4468, 4473, 4475, 4479, 4483, 4487, 4491, 4493, 4496, 4498, 4501, 4511, 4513, 4517, 4521, 4524, 4530, 4539, 4541, 4543, 4544, 4545, 4546, 4547, 4549, 4550, 4559, 4563, 4564, 4565, 4572, 4576, 4578, 4581, 4582, 4583, 4585, 4586, 4587, 4588, 4589, 4602, 4603, 4606, 4608, 4610, 4611, 4627, 4635, 4636, 4638, 4640, 4647, 4651, 4656, 4660, 4666, 4669, 4672, 4673, 4681, 4690, 4693, 4695, 4698, 4699, 4703, 4710, 4711, 4712, 4715, 4718, 4719, 4724, 4731, 4732, 4733, 4735, 4737, 4740, 4745, 4746, 4747, 4754, 4757, 4758, 4760, 4761, 4770, 4778, 4782, 4793, 4794, 4798, 4800, 4812, 4816, 4817, 4826, 4831, 4833, 4841, 4861, 4862, 4873, 4876, 4878, 4881, 4886, 4888, 4890, 4894, 4897, 4898, 4899, 4901, 4902, 4906, 4909, 4910, 4912, 4918, 4924, 4933, 4937, 4938, 4941, 4944, 4945, 4951, 4955, 4958, 4962, 4964, 4965, 4968, 4972, 4974, 4975, 4978, 4980, 4981, 4988, 4989, 4995, 4997, 5004, 5008, 5009, 5014, 5015, 5020, 5023, 5026, 5030, 5032, 5034, 5041, 5049, 5053, 5065, 5066, 5067, 5074, 5078, 5082, 5083, 5087, 5088, 5092, 5094, 5095, 5099, 5101, 5102, 5105, 5107, 5113, 5118, 5123, 5125, 5126, 5128, 5130, 5135, 5144, 5151, 5153, 5155, 5159, 5173, 5180, 5181, 5182, 5184, 5186, 5189, 5190, 5192, 5194, 5195, 5205, 5206, 5214, 5217, 5218, 5221, 5231, 5235, 5242, 5256, 5266, 5268, 5272, 5274, 5278, 5286, 5287, 5290, 5294, 5295, 5298, 5302, 5309, 5315, 5324, 5328, 5331, 5332, 5334, 5335, 5344, 5346, 5349, 5351, 5353, 5357, 5367, 5370, 5372, 5379, 5381, 5391, 5394, 5398, 5399, 5403, 5409, 5410, 5413, 5417, 5418, 5422, 5423, 5424, 5425, 5426, 5430, 5438, 5443, 5444, 5445, 5450, 5455, 5459, 5462, 5472, 5473, 5475, 5478, 5479, 5483, 5484, 5489, 5493, 5495, 5496, 5497, 5498, 5504, 5511, 5516, 5520, 5521, 5522, 5524, 5527, 5533, 5534, 5541, 5547, 5551, 5571, 5572, 5573, 5574, 5579, 5585, 5589, 5591, 5596, 5597, 5599, 5605, 5606, 5609, 5611, 5615, 5616, 5619, 5621, 5623, 5626, 5630, 5632, 5635, 5643, 5644, 5646, 5647, 5650, 5662, 5665, 5680, 5707, 5716, 5721, 5726, 5731, 5788, 5799, 5800, 5809, 5812, 5822, 5833, 5844, 5853, 5865, 5873, 5887, 5903, 5905, 5927, 5938, 5949, 5958, 5972, 5974, 5975, 5977, 5981, 6006, 6014, 6020, 6024, 6029, 6032, 6049, 6054, 6059, 6065, 6070, 6072, 6080, 6081, 6097, 6101, 6111, 6115, 6116, 6129, 6134, 6137, 6150, 6168, 6180, 6187, 6198, 6200, 6213, 6246, 6247, 6252, 6257, 6259, 6271, 6272, 6277, 6286, 6292, 6296, 6302, 6314, 6315, 6338, 6353, 6373, 6382, 6383, 6388, 6390, 6399, 6405, 6407, 6411, 6417, 6420, 6440, 6461, 6468, 6479, 6507, 6510, 6511, 6512, 6513, 6515, 6522, 6536, 6538, 6539, 6548, 6554, 6558, 6562, 6566, 6567, 6568, 6585, 6588, 6593, 6594, 6598, 6599, 6601, 6605, 6614, 6619, 6626, 6627, 6635, 6637, 6649, 6653, 6663, 6679, 6681, 6686, 6691, 6705, 6707, 6709, 6720, 6722, 6723, 6739, 6745, 6747, 6755, 6766, 6771, 6774, 6775, 6785, 6787, 6799, 6801, 6811, 6816, 6827, 6828, 6837, 6841, 6844, 6845, 6847, 6848, 6850, 6851, 6853, 6854, 6856, 6857, 6862, 6863, 6864, 6865, 6866, 6867, 6873, 6877, 6888, 6890, 6892, 6894, 6895, 6901, 6903, 6908, 6911, 6918, 6922, 6929, 6933, 6935, 6936, 6941, 6943, 6944, 6945, 6947, 6948, 6963, 6971, 6988, 6998, 7003, 7006, 7014, 7015, 7027, 7037, 7045, 7050, 7058, 7061, 7062, 7070, 7071, 7077, 7078, 7080, 7082, 7084, 7088, 7090, 7091, 7109, 7111, 7121, 7122, 7133, 7139, 7142, 7144, 7149, 7151, 7158, 7163, 7171, 7172, 7190, 7197, 7201, 7208, 7213, 7215, 7220, 7221, 7222, 7224, 7225, 7227, 7235, 7251, 7260, 7262, 7275, 7286, 7292, 7295, 7298, 7311, 7315, 7317, 7319, 7329, 7336, 7338, 7345, 7346, 7349, 7351, 7354, 7356, 7368, 7370, 7381, 7383, 7386, 7387, 7392, 7394, 7396, 7411, 7415, 7419, 7422, 7423, 7425, 7433, 7434, 7437, 7446, 7448, 7449, 7451, 7454, 7456, 7458, 7460, 7461, 7464, 7465, 7467, 7470, 7471, 7473, 7481, 7488, 7490, 7495, 7496, 7497, 7501, 7503, 7504, 7506, 7507, 7510, 7511, 7513, 7526, 7530, 7531, 7534, 7540, 7547, 7559, 7561, 7567, 7572, 7578, 7586, 7590, 7596, 7600, 7601, 7603, 7610, 7611, 7615, 7618, 7625, 7633, 7635, 7637, 7643, 7644, 7647, 7649, 7650, 7662, 7666, 7669, 7675, 7676, 7680, 7681, 7685, 7696, 7698, 7707, 7710, 7715, 7716, 7717, 7724, 7733, 7734, 7735, 7747, 7748, 7749, 7754, 7758, 7762, 7763, 7764, 7765, 7767, 7770, 7776, 7779, 7793, 7796, 7800, 7801, 7802, 7803, 7813, 7819, 7821, 7824, 7829, 7851, 7854, 7877, 7878, 7879, 7888, 7895, 7896, 7897, 7898, 7905, 7912, 7922, 7923, 7941, 7945, 7946, 7994, 7995, 7997, 8000, 8013, 8023, 8027, 8028, 8029, 8033, 8036, 8042, 8044, 8047, 8072, 8079, 8086, 8099, 8103, 8108, 8109, 8114, 8125, 8129, 8141, 8142, 8145, 8147, 8155, 8158, 8161, 8170, 8175, 8178, 8184, 8185, 8190, 8191, 8194, 8201, 8204, 8208, 8215, 8220, 8222, 8227, 8234, 8236, 8239, 8240, 8244, 8257, 8263, 8270, 8291, 8292, 8295, 8299, 8300, 8302, 8310, 8311, 8313, 8316, 8317, 8327, 8329, 8332, 8342, 8350, 8355, 8356, 8359, 8360, 8361, 8364, 8367, 8371, 8372, 8375, 8379, 8388, 8395, 8398, 8407, 8419, 8424, 8426, 8428, 8429, 8430, 8433, 8442, 8444, 8445, 8446, 8447, 8460, 8463, 8467, 8469, 8480, 8481, 8483, 8484, 8485, 8494, 8496, 8499, 8508, 8510, 8514, 8519, 8521, 8532, 8533, 8539, 8540, 8544, 8545, 8547, 8549, 8553, 8559, 8560, 8562, 8563, 8565, 8567, 8570, 8571, 8573, 8575, 8577, 8579, 8580, 8589, 8595, 8601, 8604, 8606, 8608, 8609, 8610, 8614, 8615, 8623, 8629, 8636, 8637, 8638, 8643, 8646, 8665, 8666, 8667, 8669, 8670, 8672, 8673, 8676, 8683, 8689, 8702, 8703, 8708, 8709, 8713, 8725, 8728, 8737, 8738, 8752, 8753, 8768, 8769, 8772, 8775, 8782, 8786, 8794, 8796, 8797, 8802, 8804, 8809, 8813, 8835, 8840, 8842, 8851, 8855, 8857, 8861, 8867, 8883, 8891, 8895, 8898, 8901, 8911, 8918, 8920, 8922, 8925, 8927, 8928, 8929, 8940, 8941, 8950, 8952, 8956, 8962, 8963, 8978, 8980, 8987, 8988, 8993, 8995, 8996, 9002, 9008, 9010, 9017, 9021, 9023, 9024, 9026, 9043, 9048, 9049, 9066, 9070, 9071, 9072, 9077, 9079, 9080, 9081, 9086, 9096, 9106, 9114, 9115, 9116, 9120, 9133, 9135, 9139, 9140, 9141, 9143, 9148, 9156, 9158, 9162, 9165, 9166, 9167, 9169, 9171, 9172, 9173, 9178, 9179, 9182, 9192, 9197, 9203, 9204, 9205, 9208, 9210, 9217, 9218, 9219, 9224, 9225, 9231, 9234, 9239, 9240, 9242, 9247, 9251, 9255, 9260, 9264, 9265, 9267, 9271, 9272, 9280, 9284, 9287, 9291, 9296, 9299, 9300, 9314, 9317, 9319, 9321, 9324, 9339, 9341, 9344, 9353, 9372, 9377, 9382, 9383, 9387, 9389, 9407, 9409, 9412, 9414, 9425, 9434, 9435, 9436, 9443, 9444, 9451, 9457, 9459, 9462, 9463, 9467, 9470, 9473, 9482, 9490, 9491, 9492, 9500, 9503, 9504, 9515, 9516, 9517, 9527, 9535, 9539, 9540, 9546, 9547, 9558, 9561, 9562, 9574, 9581, 9583, 9596, 9599, 9603, 9628, 9630, 9634, 9640, 9652, 9656, 9659, 9672, 9679, 9680, 9686, 9689, 9696, 9708, 9713, 9728, 9735, 9740, 9741, 9765, 9766, 9768, 9775, 9776, 9785, 9788, 9789, 9802, 9809, 9813, 9814, 9816, 9818, 9819, 9820, 9821, 9824, 9825, 9826, 9830, 9835, 9846, 9850, 9854, 9862, 9869, 9873, 9878, 9879, 9880, 9882, 9884, 9886, 9892, 9893, 9894, 9898, 9899, 9900, 9923, 9933, 9938, 9942, 9945, 9947, 9948, 9952, 9957, 9962, 9963, 9965, 9966, 9968, 9971, 9973, 9976, 9979, 9983, 9989, 9990, 9995, 9996, 10000, 10004, 10006, 10010, 10011, 10012, 10013, 10015, 10017, 10022, 10024, 10025, 10028, 10029, 10030, 10032, 10033, 10037, 10040, 10048, 10056, 10065, 10067, 10076, 10078, 10082, 10085, 10088, 10100, 10104, 10109, 10110, 10115, 10117, 10123, 10126, 10127, 10133, 10137, 10141, 10144, 10148, 10151, 10153, 10160, 10164, 10170, 10174, 10177, 10181, 10182, 10185, 10194, 10198, 10202, 10205, 10206, 10214, 10215, 10216, 10227, 10229, 10231, 10237, 10239, 10240, 10242, 10249, 10253, 10255, 10256, 10262, 10263, 10264, 10266, 10267, 10274, 10275, 10283, 10286, 10287, 10290, 10295, 10297, 10306, 10308, 10309, 10321, 10326, 10327, 10333, 10334, 10337, 10341, 10343, 10346, 10349, 10356, 10364, 10365, 10371, 10378, 10382, 10383, 10384, 10388, 10389, 10394, 10395, 10396, 10397, 10402, 10403, 10404, 10410, 10415, 10424, 10429, 10438, 10440, 10446, 10447, 10448, 10460, 10464, 10467, 10468, 10478, 10482, 10487, 10489, 10491, 10493, 10494, 10497, 10499, 10501, 10503, 10504, 10508, 10510, 10514, 10521, 10527, 10535, 10542, 10544, 10551, 10552, 10557, 10569, 10574, 10575, 10577, 10578, 10579, 10584, 10586, 10587, 10590, 10599, 10602, 10604, 10608, 10611, 10616, 10617, 10620, 10627, 10632, 10633, 10646, 10647, 10657, 10662, 10666, 10668, 10670, 10682, 10684, 10692, 10693, 10699, 10700, 10701, 10702, 10708, 10710, 10711, 10712, 10713, 10715, 10724, 10729, 10735, 10744, 10754, 10756, 10759, 10760, 10768, 10771, 10779, 10788, 10791, 10796, 10797, 10800, 10805, 10808, 10812, 10813, 10814, 10825, 10828, 10831, 10835, 10837, 10841, 10856, 10857, 10858, 10861, 10862, 10875, 10884, 10886, 10887, 10893, 10897, 10898, 10899, 10928, 10932, 10933, 10939, 10943, 10956, 10958, 10961, 10966, 10979, 10982, 10983, 10985, 10986, 10988, 10989, 10993, 10999, 11000, 11002, 11004, 11005, 11007, 11009, 11017, 11020, 11023, 11024, 11026, 11031, 11033, 11035, 11041, 11053, 11057, 11060, 11068, 11069, 11071, 11080, 11090, 11091, 11098, 11101, 11103, 11104, 11105, 11112, 11122, 11127, 11133, 11134, 11137, 11138, 11143, 11176, 11177, 11178, 11180, 11186, 11188, 11191, 11193, 11205, 11209, 11210, 11219, 11223, 11224, 11225, 11226, 11227, 11228, 11229, 11236, 11237, 11238, 11240, 11243, 11256, 11258, 11267, 11269, 11270, 11271, 11272, 11274, 11276, 11290, 11292, 11295, 11300, 11307, 11308, 11310, 11315, 11319, 11320, 11321, 11326, 11331, 11334, 11339, 11343, 11344, 11345, 11350, 11355, 11358, 11367, 11370, 11372, 11373, 11376, 11378, 11380, 11392, 11400, 11403, 11404, 11408, 11412, 11417, 11419, 11420, 11421, 11423, 11424, 11425, 11429, 11437, 11442, 11447, 11448, 11449, 11450, 11452, 11453, 11458, 11462, 11464, 11465, 11466, 11467, 11477, 11480, 11485, 11492, 11494, 11497, 11509, 11518, 11519, 11523, 11526, 11527, 11530, 11531, 11533, 11535, 11539, 11543, 11544, 11545, 11547, 11557, 11558, 11563, 11575, 11577, 11584, 11585, 11586, 11590, 11594, 11595, 11596, 11603, 11606, 11609, 11613, 11617, 11623, 11629, 11630, 11631, 11646, 11651, 11653, 11656, 11657, 11660, 11664, 11666, 11679, 11687, 11691, 11692, 11695, 11700, 11706, 11713, 11715, 11717, 11718, 11724, 11729, 11734, 11738, 11739, 11751, 11756, 11760, 11762, 11765, 11771, 11786, 11788, 11791, 11792, 11793, 11796, 11797, 11799, 11801, 11802, 11805, 11808, 11811, 11813, 11817, 11822, 11828, 11834, 11837, 11841, 11847, 11849, 11860, 11861, 11867, 11868, 11869, 11877, 11884, 11887, 11891, 11894, 11896, 11897, 11898, 11899, 11902, 11905, 11919, 11920, 11928, 11932, 11939, 11943, 11946, 11949, 11950, 11956, 11958, 11964, 11975, 11982, 11987, 11990, 11992, 11995, 11999, 12005, 12008, 12010, 12012, 12014, 12016, 12017, 12018, 12019, 12023, 12027, 12028, 12034, 12043, 12044, 12046, 12051, 12054, 12056, 12061, 12065, 12066, 12069, 12071, 12072, 12073, 12077, 12082, 12083, 12084, 12092, 12093, 12110, 12114, 12115, 12116, 12118, 12121, 12124, 12129, 12138, 12139, 12156, 12158, 12160, 12162, 12163, 12172, 12176, 12182, 12183, 12187, 12188, 12195, 12197, 12208, 12209, 12211, 12213, 12214, 12219, 12220, 12223, 12225, 12227, 12229, 12231, 12232, 12252, 12257, 12258, 12266, 12277, 12278, 12279, 12290, 12292, 12294, 12297, 12303, 12305, 12307, 12316, 12318, 12325, 12331, 12341, 12354, 12356, 12368, 12369, 12370, 12371, 12372, 12373, 12377, 12382, 12386, 12387, 12390, 12405, 12406, 12408, 12414, 12415, 12421, 12424, 12427, 12429, 12430, 12435, 12443, 12448, 12453, 12459, 12465, 12466, 12468, 12481, 12483, 12488, 12489, 12490, 12491, 12492, 12498, 12501, 12503, 12505, 12511, 12516, 12517, 12518, 12519, 12523, 12524, 12527, 12528, 12534, 12544, 12547, 12550, 12553, 12554, 12555, 12565, 12566, 12569, 12570, 12572, 12575, 12576, 12577, 12580, 12581, 12583, 12585, 12588, 12589, 12590, 12591, 12594, 12597, 12599, 12605, 12607, 12609, 12611, 12612, 12613, 12622, 12625, 12626, 12635, 12645, 12646, 12647, 12651, 12652, 12657, 12662, 12667, 12672, 12673, 12674, 12675, 12676, 12680, 12681, 12688, 12691, 12694, 12696, 12701, 12702, 12703, 12705, 12716, 12718, 12719, 12720, 12724, 12729, 12730, 12731, 12733, 12734, 12735, 12736, 12740, 12746, 12750, 12752, 12755, 12763, 12764, 12767, 12771, 12773, 12782, 12786, 12787, 12788, 12795, 12796, 12798, 12800, 12803, 12808, 12809, 12810, 12811, 12815, 12818, 12819, 12820, 12822, 12824, 12826, 12827, 12832, 12833, 12835, 12847, 12848, 12854, 12860, 12861, 12863, 12868, 12869, 12874, 12876, 12882, 12883, 12885, 12887, 12888, 12893, 12901, 12903, 12904, 12907, 12909, 12910, 12916, 12925, 12936, 12937, 12939, 12947, 12951, 12958, 12960, 12961, 12962, 12965, 12967, 12977, 12980, 12986, 12989, 12991, 12993, 12994, 12995, 12999, 13012, 13013, 13015, 13020, 13023, 13026, 13031, 13048, 13050, 13051, 13057, 13063, 13066, 13067, 13071, 13072, 13073, 13074, 13081, 13084, 13085, 13093, 13096, 13101, 13102, 13114, 13116, 13117, 13122, 13124, 13130, 13131, 13132, 13133, 13137, 13142, 13152, 13160, 13166, 13167, 13168, 13171, 13174, 13175, 13179, 13183, 13184, 13187, 13192, 13194, 13196, 13200, 13206, 13207, 13210, 13216, 13219, 13223, 13224, 13229, 13235, 13241, 13249, 13251, 13253, 13255, 13261, 13265, 13266, 13268, 13272, 13274, 13278, 13279, 13280, 13281, 13287, 13297, 13303, 13307, 13311, 13315, 13317, 13318, 13320, 13322, 13324, 13327, 13330, 13332, 13334, 13337, 13342, 13346, 13353, 13356, 13357, 13362, 13372, 13373, 13374, 13378, 13382, 13384, 13388, 13389, 13390, 13405, 13408, 13410, 13413, 13415, 13417, 13423, 13424, 13429, 13430, 13438, 13441, 13444, 13445, 13449, 13452, 13453, 13457, 13459, 13460, 13468, 13470, 13476, 13477, 13479, 13481, 13495, 13496, 13498, 13501, 13510, 13511, 13512, 13515, 13516, 13518, 13525, 13528, 13530, 13532, 13533, 13538, 13539, 13544, 13545, 13546, 13549, 13550, 13553, 13554, 13556, 13561, 13563, 13564, 13565, 13567, 13568, 13574, 13577, 13580, 13583, 13585, 13586, 13597, 13604, 13605, 13607, 13608, 13611, 13613, 13617, 13618, 13622, 13623, 13632, 13633, 13635, 13636, 13638, 13641, 13642, 13643, 13647, 13649, 13653, 13655, 13656, 13662, 13668, 13670, 13671, 13678, 13681, 13687, 13691, 13694, 13699, 13701, 13703, 13705, 13706, 13708, 13711, 13714, 13719, 13724, 13726, 13727, 13730, 13735, 13737, 

In [68]:
not_null_list = []
for i in range(len(data_set)):
  if pd.notna(data_set['one_sentence_summ'][i]) and pd.notna(data_set['tldrs'][i]):
    not_null_list.append(i)
print(not_null_list)
print(len(not_null_list))

[]
0

In [32]:
data_set['keywords'].isna().sum()

2160

In [33]:
data_set['abstracts'].isna().sum()

10

In [48]:
abstract_nan = pd.isna(data_set['abstracts'])
abstract_nan = data_set[abstract_nan]
abstract_nan

,urls,titles,keywords,tldrs,abstracts,one_sentence_summ
237,https://openreview.net/forum?id=SJUdkecgx,NaN,NaN,We propose:,NaN,NaN
2511,https://openreview.net/forum?id=SkgYciAqF7,NaN,NaN,NaN,NaN,NaN
2549,https://openreview.net/forum?id=SkeiPsAqK7,NaN,NaN,NaN,NaN,NaN
2664,https://openreview.net/forum?id=Sy4G8sC9KX,NaN,NaN,NaN,NaN,NaN
2676,https://openreview.net/forum?id=r1MmH30cY7,NaN,NaN,NaN,NaN,NaN
2685,https://openreview.net/forum?id=SkgD4jAcYX,NaN,NaN,NaN,NaN,NaN
2770,https://openreview.net/forum?id=r1xce3ActX,NaN,NaN,NaN,NaN,NaN
2917,https://openreview.net/forum?id=HJgHwi0ctm,NaN,NaN,NaN,NaN,NaN
2944,https://openreview.net/forum?id=B1GRtj05t7,NaN,NaN,NaN,NaN,NaN
2978,https://openreview.net/forum?id=rylRgh0qK7,NaN,NaN,NaN,NaN,NaN

In [59]:
abstract_nan.index.tolist()

[237, 2511, 2549, 2664, 2676, 2685, 2770, 2917, 2944, 2978]

In [69]:
data_set['combined'] = data_set['tldrs'].fillna(data_set['one_sentence_summ'])
data_set

,urls,titles,keywords,tldrs,abstracts,one_sentence_summ,combined
0,https://openreview.net/forum?id=Sy8gdB9xx,Understanding deep learning requires rethinkin...,Deep learning,"Through extensive systematic experiments, we s...","Despite their massive size, successful deep ar...",NaN,"Through extensive systematic experiments, we s..."
1,https://openreview.net/forum?id=r1Ue8Hcxg,Neural Architecture Search with Reinforcement ...,NaN,NaN,Neural networks are powerful and flexible mode...,NaN,NaN
2,https://openreview.net/forum?id=Hk4_qw5xe,Towards Principled Methods for Training Genera...,NaN,We introduce a theory about generative adversa...,The goal of this paper is not to introduce a s...,NaN,We introduce a theory about generative adversa...
3,https://openreview.net/forum?id=HJ0NvFzxl,Learning Graphical State Transitions,Natural language processing; Deep learning; Su...,I introduce a set of differentiable graph tran...,Graph-structured data is important in modeling...,NaN,I introduce a set of differentiable graph tran...
4,https://openreview.net/forum?id=HkwoSDPgg,Semi-supervised Knowledge Transfer for Deep Le...,NaN,Semi-supervised learning of a privacy-preservi...,Some machine learning applications involve tra...,NaN,Semi-supervised learning of a privacy-preservi...
...,...,...,...,...,...,...,...
24473,https://openreview.net/forum?id=1bbPQShCT2,I-PHYRE: Interactive Physical Reasoning,Intuitive physics; physical reasoning,Build human-level interactive agents that can ...,Current evaluation protocols predominantly ass...,NaN,Build human-level interactive agents that can ...
24474,https://openreview.net/forum?id=Ny150AblPu,Exposing Text-Image Inconsistency Using Diffus...,inconsistency detection; multi-modal learning;...,NaN,In the battle against widespread online misinf...,NaN,NaN
24475,https://openreview.net/forum?id=ZGBOfAQrMl,Video Super-Resolution Transformer with Masked...,video super-resolution; adaptive; memory and c...,NaN,"Recently, Vision Transformer has achieved grea...",NaN,NaN
24476,https://openreview.net/forum?id=J2kRjUAOLh,Contrastive Predict-and-Search for Mixed Integ...,Mixed integer programs; contrastive learning,We use contrastive learning to predict solutio...,Mixed integer linear programs (MILP) are flex...,NaN,We use contrastive learning to predict solutio...
24477,https://openreview.net/forum?id=U0P622bfUN,Federated Generative Learning with Foundation ...,federated learning; non-iid data,We propose a novel federated learning framewor...,Existing federated learning solutions focus on...,NaN,We propose a novel federated learning framewor...

In [79]:
new_dataset = data_set.drop(['tldrs', 'one_sentence_summ'], axis=1)
new_dataset

,urls,titles,keywords,abstracts,combined
0,https://openreview.net/forum?id=Sy8gdB9xx,Understanding deep learning requires rethinkin...,Deep learning,"Despite their massive size, successful deep ar...","Through extensive systematic experiments, we s..."
1,https://openreview.net/forum?id=r1Ue8Hcxg,Neural Architecture Search with Reinforcement ...,NaN,Neural networks are powerful and flexible mode...,NaN
2,https://openreview.net/forum?id=Hk4_qw5xe,Towards Principled Methods for Training Genera...,NaN,The goal of this paper is not to introduce a s...,We introduce a theory about generative adversa...
3,https://openreview.net/forum?id=HJ0NvFzxl,Learning Graphical State Transitions,Natural language processing; Deep learning; Su...,Graph-structured data is important in modeling...,I introduce a set of differentiable graph tran...
4,https://openreview.net/forum?id=HkwoSDPgg,Semi-supervised Knowledge Transfer for Deep Le...,NaN,Some machine learning applications involve tra...,Semi-supervised learning of a privacy-preservi...
...,...,...,...,...,...
24473,https://openreview.net/forum?id=1bbPQShCT2,I-PHYRE: Interactive Physical Reasoning,Intuitive physics; physical reasoning,Current evaluation protocols predominantly ass...,Build human-level interactive agents that can ...
24474,https://openreview.net/forum?id=Ny150AblPu,Exposing Text-Image Inconsistency Using Diffus...,inconsistency detection; multi-modal learning;...,In the battle against widespread online misinf...,NaN
24475,https://openreview.net/forum?id=ZGBOfAQrMl,Video Super-Resolution Transformer with Masked...,video super-resolution; adaptive; memory and c...,"Recently, Vision Transformer has achieved grea...",NaN
24476,https://openreview.net/forum?id=J2kRjUAOLh,Contrastive Predict-and-Search for Mixed Integ...,Mixed integer programs; contrastive learning,Mixed integer linear programs (MILP) are flex...,We use contrastive learning to predict solutio...
24477,https://openreview.net/forum?id=U0P622bfUN,Federated Generative Learning with Foundation ...,federated learning; non-iid data,Existing federated learning solutions focus on...,We propose a novel federated learning framewor...

In [86]:
new_dataset = new_dataset.rename(columns={'combined':'one_sentence_summary'})

In [87]:
new_dataset.to_csv('new_collection.csv', encoding='utf-8', index=False)